spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guard_db?serverTimezone=Asia/Seoul
    username: root
    password: root3306

  jpa:
    hibernate:
      ddl-auto: update   # 또는 create / create-drop (테스트용)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: thisisaverysecurekeythatyoustoreexternally123!
  expiration: 3600000 # 1시간 (단위: 밀리초)

server:
  port: 8080
